(cl:defpackage ur3_driver-msg
  (:use )
  (:export
   "<COMMAND>"
   "COMMAND"
   "<GRIPPER_INPUT>"
   "GRIPPER_INPUT"
   "<POSITION>"
   "POSITION"
   "<ROBOT1_COMMAND>"
   "ROBOT1_COMMAND"
   "<ROBOT1_GRIPPER_INPUT>"
   "ROBOT1_GRIPPER_INPUT"
   "<ROBOT1_POSITION>"
   "ROBOT1_POSITION"
   "<ROBOT2_COMMAND>"
   "ROBOT2_COMMAND"
   "<ROBOT2_GRIPPER_INPUT>"
   "ROBOT2_GRIPPER_INPUT"
   "<ROBOT2_POSITION>"
   "ROBOT2_POSITION"
  ))

