// Generated by gencpp from file ur3_driver/robot2_gripper_input.msg
// DO NOT EDIT!


#ifndef UR3_DRIVER_MESSAGE_ROBOT2_GRIPPER_INPUT_H
#define UR3_DRIVER_MESSAGE_ROBOT2_GRIPPER_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur3_driver
{
template <class ContainerAllocator>
struct robot2_gripper_input_
{
  typedef robot2_gripper_input_<ContainerAllocator> Type;

  robot2_gripper_input_()
    : DIGIN_2(0)
    , AIN0_2(0.0)
    , AIN1_2(0.0)  {
    }
  robot2_gripper_input_(const ContainerAllocator& _alloc)
    : DIGIN_2(0)
    , AIN0_2(0.0)
    , AIN1_2(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _DIGIN_2_type;
  _DIGIN_2_type DIGIN_2;

   typedef double _AIN0_2_type;
  _AIN0_2_type AIN0_2;

   typedef double _AIN1_2_type;
  _AIN1_2_type AIN1_2;





  typedef boost::shared_ptr< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> const> ConstPtr;

}; // struct robot2_gripper_input_

typedef ::ur3_driver::robot2_gripper_input_<std::allocator<void> > robot2_gripper_input;

typedef boost::shared_ptr< ::ur3_driver::robot2_gripper_input > robot2_gripper_inputPtr;
typedef boost::shared_ptr< ::ur3_driver::robot2_gripper_input const> robot2_gripper_inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur3_driver::robot2_gripper_input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur3_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ur3_driver': ['/home/ur3/catkin_yuhaow7/src/drivers/ur3_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5cac449f67c506d08572b8886dce274";
  }

  static const char* value(const ::ur3_driver::robot2_gripper_input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5cac449f67c506dULL;
  static const uint64_t static_value2 = 0x08572b8886dce274ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur3_driver/robot2_gripper_input";
  }

  static const char* value(const ::ur3_driver::robot2_gripper_input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 DIGIN_2 \n\
float64 AIN0_2\n\
float64 AIN1_2\n\
";
  }

  static const char* value(const ::ur3_driver::robot2_gripper_input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.DIGIN_2);
      stream.next(m.AIN0_2);
      stream.next(m.AIN1_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot2_gripper_input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur3_driver::robot2_gripper_input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur3_driver::robot2_gripper_input_<ContainerAllocator>& v)
  {
    s << indent << "DIGIN_2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.DIGIN_2);
    s << indent << "AIN0_2: ";
    Printer<double>::stream(s, indent + "  ", v.AIN0_2);
    s << indent << "AIN1_2: ";
    Printer<double>::stream(s, indent + "  ", v.AIN1_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR3_DRIVER_MESSAGE_ROBOT2_GRIPPER_INPUT_H
